---
pdf_document:
  toc: yes
author: ''
date: ''
output:
  pdf_document: default
  toc: yes
theme: united
title: "Results of taxonomic harmonizations"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r load data}
d <- read_rds(
  here::here("data/data_cleaned/biotime_results/harmonized.rds")
)
common <- read_csv(
  here::here("data/data_cleaned/biotime_results/biotime_common.csv")
  ) %>% 
  select(-class, -phylum) %>% 
  mutate(common = modify(common, function(x)
    ifelse(is.na(x) | x == "mammals", "other", x)))
```

```{r bogota}
bogota <- d$bogota %>% 
  filter(!is.na(binomial)) %>% 
  transmute(binomial,
            common = modify(common, function(x) 
              ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "Bogota")
```

```{r torino}
torino <- d$torino %>% 
  filter(!is.na(binomial)) %>% 
  transmute(binomial,
            common = modify(common, function(x) 
              ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "Torino")
```

```{r gbif preprocessed}
gbif_prep <- d$gbif_preproc %>% 
  filter(!is.na(binomial)) %>% 
  mutate(common = modify(common, function(x) 
    ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "GBIF pre-processed")
```

```{r gbif only}
gbif <- d$gbif %>% 
  filter(!is.na(binomial)) %>% 
  mutate(common = modify(common, function(x) 
    ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "GBIF only")
```

```{r table of results}
res <- bogota %>% 
  bind_rows(torino) %>% 
  bind_rows(gbif_prep) %>%
  bind_rows(gbif) %>% 
  pivot_longer(1:4, names_to = "common", values_to = "n") %>% 
  pivot_wider(names_from = workflow, values_from = n)
```

In the *other* row, the 26 species are: 1 bird (*Turdus pallidus*), 24 vascular plants, and 1 fish (see below for the list).

```{r differences}
wf_diff <- d$bogota %>% 
  transmute(parsed, bogota = binomial,
            common = pmap(list(ebird, fishbase, lcvp), function(x, y, z) {
              if (!is.na(x))
                "birds"
              else if (!is.na(y))
                "fishes"
              else
                "plants"
            }) %>% unlist()) %>% 
  distinct_all() %>% 
  left_join(d$torino %>% 
              transmute(parsed, torino = binomial) %>% 
              distinct_all()) %>%
  mutate(bogota = modify(bogota, function(x) ifelse(is.na(x), "NA", x)),
         torino = modify(torino, function(x) ifelse(is.na(x), "NA", x))) %>% 
  filter(bogota != torino)

wf_diff %>% 
  pull(common) %>% 
  table()

wf_diff %>% 
  pull(bogota)
```
# Unique names

Same procedure, but removing duplicate rows.

```{r bogota uniq, include=FALSE}
bogota <- d$bogota %>% 
  filter(!is.na(binomial)) %>% 
  transmute(binomial,
            common = modify(common, function(x) 
              ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  distinct(binomial, .keep_all = TRUE) %>%   group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "Bogota")
```

```{r torino uniq, include=FALSE}
torino <- d$torino %>% 
  filter(!is.na(binomial)) %>% 
  transmute(binomial,
            common = modify(common, function(x) 
              ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  distinct(binomial, .keep_all = TRUE) %>% 
  group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "Torino")
```

```{r gbif preprocessed uniq, include=FALSE}
gbif_prep <- d$gbif_preproc %>% 
  filter(!is.na(binomial)) %>% 
  mutate(common = modify(common, function(x) 
    ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  distinct(binomial, .keep_all = TRUE) %>% 
  group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "GBIF pre-processed")
```

```{r gbif only uniq, include=FALSE}
gbif <- d$gbif %>% 
  filter(!is.na(binomial)) %>% 
  mutate(common = modify(common, function(x) 
    ifelse(is.na(x) | x == "mammals", "other", x))) %>% 
  distinct(binomial, .keep_all = TRUE) %>% 
  group_by(common) %>% 
  tally() %>% 
  pivot_wider(names_from = common, values_from = n) %>% 
  add_column(workflow = "GBIF only")
```

```{r table of results uniq, include=FALSE}
res_unique <- bogota %>% 
  bind_rows(torino) %>% 
  bind_rows(gbif_prep) %>% 
  bind_rows(gbif) %>%
  pivot_longer(1:4, names_to = "common", values_to = "n") %>% 
  pivot_wider(names_from = workflow, values_from = n)
```

The first table shows the number of species names found and the second the number of unique species names found.

```{r results}
# I reassign them to the correct taxonomig group
res$Bogota[1] <- res$Bogota[1] + 1
res$Bogota[2] <- res$Bogota[2] + 1
res$Bogota[3] <- NA
res$Bogota[4] <- res$Bogota[4] + 24

res_unique$Bogota[1] <- res_unique$Bogota[1] + 1
res_unique$Bogota[2] <- res_unique$Bogota[2] + 1
res_unique$Bogota[3] <- NA
res_unique$Bogota[4] <- res_unique$Bogota[4] + 24

res %>% knitr::kable()
res_unique %>% knitr::kable()
```
















